Output try-rs.gif

Set Width 1400
Set Height 800

Require try-rs

Set Shell fish

Type "try-rs"
Enter
Sleep 3s
Down
Sleep 3s
Down
Sleep 3s
Down
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Up
Sleep 3s
Up
Sleep 4s
Ctrl+D
Sleep 5s
Type n 
Sleep 5s
Ctrl+A
Sleep 6s
Escape
Sleep 3s
Ctrl+T
Sleep 4s
Escape
Sleep 3s
Type "NewProject"
Sleep 3s
Enter
Sleep 1s
Type "try-rs"
Sleep 2s
Enter
Sleep 5s
Escape
Sleep 5s
Type "try-rs --help"
Sleep 5s
Enter
Sleep 5s
Type "exit"


