Output sample.gif

Set Width 1400
Set Height 800

Require try-rs

Set Shell fish

Hide
Type "source ~/.config/fish/functions/try-rs.fish"
Enter
Show

Type "try-rs"
Enter
Sleep 3s
Down
Sleep 3s
Down
Sleep 3s
Down
Sleep 3s
Up
Sleep 3s
Up
Sleep 4s
Ctrl+D
Sleep 5s
Type n 
Sleep 5s
Ctrl+A
Sleep 6s
Escape
Sleep 3s
Ctrl+T
Sleep 4s
Down 
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Down 
Sleep 3s
Escape
Sleep 3s
Type "example4"
Sleep 3s
Enter
Sleep 3s
